# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: run-k8s-tests
    # Cloud Provider: AWS
    cloud: aws
    # Instance Type has 4 vcpu, 16 GiB memory, Up to 5 Gbps Network Performance
    instance_type: t3a.xlarge
    # Custom AMI with docker/cypress/hub pre-installed
    machine_image: ami-0b00778f1a4493e7c
    # Region: Oregon
    region: eu-west-1
    # Use Spot Instances for cost savings
    preemptible:
      - true
      - false
    labels:
      - cirun-runner
